[package]
name = "martin"
version = "0.8.1"
edition = "2021"
authors = ["Stepan Kuzmin <to.stepan.kuzmin@gmail.com>", "Yuri Astrakhan <YuriAstrakhan@gmail.com>", "MapLibre contributors"]
description = "Blazing fast and lightweight tile server with PostGIS, MBTiles, and PMTiles support"
repository = "https://github.com/maplibre/martin"
license = "MIT OR Apache-2.0"
keywords = ["maps", "tiles", "mbtiles", "pmtiles", "postgis"]
exclude = [
    # Tests include a lot of data and other test files that are not needed for the users of the library
    "/tests",
]

[lib]
name = "martin"
path = "src/lib.rs"

[[bin]]
name = "martin"
path = "src/bin/main.rs"

[features]
default = []
ssl = ["openssl", "postgres-openssl"]
vendored-openssl = ["ssl", "openssl/vendored"]

[dependencies]
actix = "0.13"
actix-cors = "0.6"
actix-files = "0.6"
actix-http = "3"
actix-rt = "2"
actix-web = "4"
async-trait = "0.1"
brotli = "3"
clap = { version = "4", features = ["derive"] }
deadpool-postgres = "0.10"
env_logger = "0.10"
flate2 = "1"
futures = "0.3"
itertools = "0.10"
log = "0.4"
martin-mbtiles = { path = "martin-mbtiles", version = "0.1.0" }
martin-tile-utils = { path = "martin-tile-utils", version = "0.1.0" }
num_cpus = "1"
openssl = { version = "0.10", optional = true }
pmtiles = { version = "0.2", features = ["mmap-async-tokio", "tilejson"] }
postgis = "0.9"
postgres = { version = "0.19", features = ["with-time-0_3", "with-uuid-1", "with-serde_json-1"] }
postgres-openssl = { version = "0.5", optional = true }
postgres-protocol = "0.6"
regex = "1"
semver = "1"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
serde_yaml = "0.9"
subst = { version = "0.2", features = ["yaml"] }
thiserror = "1"
tilejson = "0.3"

[dev-dependencies]
cargo-husky = { version = "1", features = ["user-hooks"], default-features = false }
criterion = { version = "0.4", features = ["async_futures", "async_tokio", "html_reports"] }
ctor = "0.2"
indoc = "2"
#test-log = "0.2"

[[bench]]
name = "sources"
harness = false

[profile.dev.package.sqlx-macros]
# See https://github.com/launchbadge/sqlx#compile-time-verification
opt-level = 3

[workspace]
default-members = ["martin-tile-utils", "martin-mbtiles", "."]
members = ["martin-tile-utils", "martin-mbtiles"]
